artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/tproma/Multiple_Projects_Data/raw/main/learn-ai-bbc.zip
  local_data_file:  artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

 
data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE:  artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["data.zip","BBC News Train.csv", "BBC News Test.csv", "BBC News Sample Solution.csv"]


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/BBC News Train.csv
  tokenizer_name: bert-base-uncased
   

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/Train BBC dataset
  val_data_path: artifacts/data_transformation/Validation BBC dataset
  model_ckpt: bert-base-uncased
   

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/Test BBC dataset
  model_path:  artifacts/model_trainer/bert-base-uncased-model
  tokenizer_path:  artifacts/model_trainer/tokenizer
  metric_file_name: artifacts/model_evaluation/metric.csv