 TrainingArguments:
    output_dir: "bert-base-cased"
    learning_rate: 2e-5
    per_device_train_batch_size: 16
    per_device_eval_batch_size: 16
    num_train_epochs: 5
    weight_decay: 0.01
    eval_steps: 50
    evaluation_strategy: "epoch"
    save_strategy: "epoch"
    load_best_model_at_end: True

    